/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`/${props.model}`)
  const { actions } = useAnimations(animations, group)

  const [pos, setPos] = useState([0, 0, 0]);
  const [act, setAct] = useState(actions);

  useEffect(() => {
    console.log(act.anime)
    act.anime.stop();
    setAct(actions)
    // act.anime
    act.anime.play();
    setPos([0, -1.4, 0])
    
  }, [props]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={pos} rotation={[Math.PI/2, 0, 0]} scale={0.01}>
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} material={materials.Alpha_Joints_MAT} skeleton={nodes.Alpha_Joints.skeleton} scale={200} />
          <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} material={materials.Alpha_Body_MAT} skeleton={nodes.Alpha_Surface.skeleton} scale={200} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/default.glb')
